### PR TITLE
Add flag for ImagePullSecert

### PR DESCRIPTION
**Pull request by vavilenski**
Added the ability to use external secrets to download images (imagePullSecret).

### CODE REVIEW

**Comment by andrey-ryoo** [comment]
Hi, you can use any secret name in registry.imagePullSecret. Just set registry.enabled: false and regcred will not be created

**Comment by cheshi-mantu** [comment]
@vavilenski please reverto the provided comment, sir. Would that be sufficient for your tasks?
thanks

**Comment by vavilenski** [comment]
@andrey-ryoo Hi, if I set registry.enabled: false then parameter imagePullSecrets  will not be used . Look here https://github.com/qameta/allure-testops-deployment/blob/master/charts/allure-testops/templates/allure/report-statefulset.yaml#L33 value imagePullSecrets work only if registry.enabled: true, but in this case secrets will be created by chart.

**Comment by andrey-ryoo** [comment]
No more conflicting. Please take a look

**Comment by vavilenski** [comment]
Yes, thank you. Now the names of the imagePullSecrets will be loaded in any case. I close the request.

**Pull request closed without merging**
